apiVersion: v1
kind: Namespace
metadata:
  name: example-monitor-pods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-pods-acc
  namespace: example-monitor-pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitor-pods
subjects:
  - kind: ServiceAccount
    name: monitor-pods-acc
    namespace: example-monitor-pods
---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
  namespace: example-monitor-pods
spec:
  containers:
  - name: shell-operator
    image: shell-operator:monitor-pods
    imagePullPolicy: Never # Always
    args: ["--log-level=debug"]
  serviceAccountName: monitor-pods-acc
